name: Python Package using Anaconda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.9"

      - name: Create Conda environment
        run: |
          conda create --name os_visualizer_env python=3.9
          conda activate os_visualizer_env
          conda install --file requirements.txt

      - name: Run Tests
        run: |
          conda activate os_visualizer_env
          pytest
